# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-27 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_auto_20200126_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='products',
        ),
    ]
