# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_remove_add_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='id',
        ),
        migrations.AlterField(
            model_name='add',
            name='nid',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
