# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_auto_20200211_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='fone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='add',
            name='nid',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
