# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 06:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_auto_20200211_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='fone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='add',
            name='name',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabet characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='add',
            name='nid',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
