# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_auto_20200212_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='user',
        ),
    ]
